In [2]:
import re

匹配一个特定的字符串

In [4]:
text = 'abc123456def789101112'
print(re.findall(r'1234567', text))

[]


\d匹配一个数字 \D非数字 \s一个空格 \S一个非空格 \w字母数字下划线 \W与小写w相反 [abcd]abcd任意字符
 [a-e]a到e的任意字符 [^a-d]取反，除a-d的任意字符 .除换行符的任意字符

In [5]:
re.findall(r'\d', text)

['1', '2', '3', '4', '5', '6', '7', '8', '9', '1', '0', '1', '1', '1', '2']

匹配一组字符

In [9]:
re.findall(r'[1234e]+', text)

['1234', 'e', '1', '1112']

+:一或者多个
*:0或多个
?:0或1个

In [10]:
re.findall(r'\d+', text)

['123456', '789101112']

匹配指定重复次数

In [16]:
re.findall(r'\d{4}', text)

['1234', '7891', '0111']

In [20]:
re.findall(r'\d{1,4}', text)

['1234', '56', '7891', '0111', '2']

组合或匹配多种模式

In [23]:
mobile_phone = '0855-7524868'
landline_phone = '13208557070'
re.findall(r'\d{3,4}-\d{7,8}|1\d{10}', landline_phone)

['13208557070']

限定位置 ^表示开头 $表示结尾 \A \Z同样分别表示匹配开头结尾 忽略m标记(跨行标记) \b 单词边界 \B 非单词边界
(?=...) 匹配...出现在之后的位置 (?!...) 匹配...不出现在之后的位置 (?<=...) 匹配...出现在之前的位置
(?!<=...)匹配...不出现在之前的位置

In [54]:
pwd = '12345678密码:123456'
re.findall(r'(?<=密码.)\d+', pwd)

['123456']

In [33]:
duplicate_words = "barbar carcar dardae"
print(re.findall(r'(\w{3})(\1)', duplicate_words))

[('bar', 'bar'), ('car', 'car')]


re模块

re.search() 查找符合模式的字符 只返回第一个 并返回Match对象
re.match() 从开头匹配 其余用法同上
re.findall() 查找所有匹配的字符
re.finditer() 返回一个迭代器
re.sub() 替换匹配的字符串
re.compile() 把正则表达式编译成一个对象

In [131]:
m = re.search(r'(\d{2,4})-(\d{7,8})', mobile_phone)
print(m.group())
print(m.group(1))
print(m.group(2))
print(m.groups())

0855-7524868
0855
7524868
('0855', '7524868')


In [140]:
test_question_mark = 'what is the problem?'
m = re.search(r'(.+)\s+(.+\s*(?=\?))', test_question_mark)
print(m.group())
print(m.groups())

what is the problem
('what is the', 'problem')
[' is the problem']


In [5]:
test_english = " What? Are     you crazy? Come on, bro, there are many things to expect, the blue sky; the sea; people you love; cheer    up and go on!"
print(re.findall(r'\w+', test_english))

['What', 'Are', 'you', 'crazy', 'Come', 'on', 'bro', 'there', 'are', 'many', 'things', 'to', 'expect', 'the', 'blue', 'sky', 'the', 'sea', 'people', 'you', 'love', 'cheer', 'up', 'and', 'go', 'on']


In [3]:
test_japanese = 'サー・マイケル・フィリップ・ジャガーの出身は？'
print(re.findall(r'\w+', test_japanese))

['サー', 'マイケル', 'フィリップ', 'ジャガーの出身は']


In [14]:
test_mix = "13 44 dfdd dsasd 1jsd"
w_pattern = re.compile(r'\w+')
d_pattern = re.compile(r'\d+')

for w in w_pattern.findall(test_mix):
    tmp = d_pattern.findall(w)
    if len(tmp) == 0:
        print(w)

dfdd
dsasd


In [21]:
a = [1, 2, 3]
b = [4, 5, 6]
c = a + b
print(a)
print(b)
print(c)

[1, 2, 3]
[4, 5, 6]
[1, 2, 3, 4, 5, 6]


In [31]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "I please love",
    "you love",
    "he is"
]

vectorizer = CountVectorizer(token_pattern=r'\w+')
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names()
print(X.toarray())
vectorizer.get_feature_names()

[[0 1 0 1 1 0]
 [0 0 0 1 0 1]
 [1 0 1 0 0 0]]


['he', 'i', 'is', 'love', 'please', 'you']

In [36]:
vec0 = CountVectorizer(token_pattern=r'\w+')
corpus = [
    'I am', ' he is', 'we are'
]
vec0.fit(corpus)
test0 = ['I am','he is','empty']
w0 = vec0.transform(test0)
print(w0.toarray())

[[1 0 0 1 0 0]
 [0 0 1 0 1 0]
 [0 0 0 0 0 0]]


In [37]:
import numpy as np
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])